dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/opensds

go:
  - 1.11.x
  - 1.12.x
  - tip

env:
  - TARGET=amd64
    GO111MODULE=on

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc
  - sudo apt-get install -y librados-dev librbd-dev
  - sudo apt-get install -y lvm2 tgt open-iscsi
<<<<<<< 0feeb98168409d1666fe427663d0ab192adb5e68
  - sudo docker pull p1c2u/openapi-spec-validator

=======
  - go get -v github.com/onsi/gomega
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get github.com/modocache/gover
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin
>>>>>>> end

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  exclude:


install:
  # Build OpenSDS Controller source code
  - make all

script:
  - ./install/CI/coverage
  - ./install/CI/test

after_failure:
  - for v in /var/log/opensds/*.log ; do
    echo $v logtail ======================== ; tail -100 $v ;
    done

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Clean OpenSDS Controller built data
  - make clean
